// <auto-generated />
using FilmCollection.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FilmCollection.Migrations
{
    [DbContext(typeof(FilmCollectionContext))]
    partial class FilmCollectionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("FilmCollection.Models.NewMovie", b =>
                {
                    b.Property<int>("film_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .HasColumnType("TEXT");

                    b.Property<string>("director")
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lent_to")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("film_id");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            film_id = 1,
                            category = "Action/Adventure",
                            director = "John Doe",
                            edited = false,
                            lent_to = "",
                            notes = "",
                            rating = "PG-13",
                            title = "Casino Royale",
                            year = 2006
                        },
                        new
                        {
                            film_id = 2,
                            category = "Action/Adventure",
                            director = "John Doe",
                            edited = false,
                            lent_to = "",
                            notes = "",
                            rating = "PG-13",
                            title = "Skyfall",
                            year = 2013
                        },
                        new
                        {
                            film_id = 3,
                            category = "Action/Adventure",
                            director = "John Doe",
                            edited = false,
                            lent_to = "",
                            notes = "",
                            rating = "PG-13",
                            title = "No Time To Die",
                            year = 2021
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
